Repository SuperCoding24/shoppingmall_frontend, pull requests merged in 2024-05, with the labels that each got.

#3 setting: 프로젝트 기본 세팅
  shoppingmall/.gitignore
  shoppingmall/README.md
  shoppingmall/package-lock.json
  shoppingmall/package.json
  shoppingmall/public/favicon.ico
  shoppingmall/public/index.html
  shoppingmall/public/logo192.png
  shoppingmall/public/logo512.png
  shoppingmall/public/manifest.json
  shoppingmall/public/robots.txt
  shoppingmall/src/App.css
  shoppingmall/src/App.js
  shoppingmall/src/App.test.js
  shoppingmall/src/components/Component.js
  shoppingmall/src/index.js
  shoppingmall/src/pages/Page.js
Labels: setting

#8 nav, footer 공통 Layout으로 만들기
  shoppingmall/src/App.js
  shoppingmall/src/components/commom/AppLayout.js
  shoppingmall/src/components/footer/Footer.js
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/index.js
  shoppingmall/src/pages/Page.js
  shoppingmall/src/pages/myPage/MyPage.js
Labels: design

#10 design : 로그인, 회원가입 UI 구현
  shoppingmall/src/App.js
  shoppingmall/src/assets/cart.svg
  shoppingmall/src/assets/email.svg
  shoppingmall/src/assets/mypage.svg
  shoppingmall/src/assets/password.svg
  shoppingmall/src/assets/people.svg
  shoppingmall/src/assets/phone.svg
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
Labels: design, feat

#18 [design] 상품 등록 페이지 UI 구현
  shoppingmall/src/App.js
  shoppingmall/src/assets/LeftArrow.svg
  shoppingmall/src/assets/Modify.svg
  shoppingmall/src/assets/date.svg
  shoppingmall/src/components/commom/ArrowButton.js
  shoppingmall/src/components/commom/CompletedButton.js
  shoppingmall/src/components/commom/HeaderText.js
  shoppingmall/src/components/commom/Pagination.js
  shoppingmall/src/components/commom/ProductComponent.js
  shoppingmall/src/components/commom/ProductItem.js
  shoppingmall/src/components/commom/SellFilter.js
  shoppingmall/src/pages/ProductRegistrationPage/ProductRegistrationPage.js
  shoppingmall/src/pages/sellPage/SellPage.js
Labels: design

#11 design: 내상품 판매 내역 페이지 UI구현
  shoppingmall/src/App.js
  shoppingmall/src/assets/LeftArrow.svg
  shoppingmall/src/assets/Modify.svg
  shoppingmall/src/pages/sellPage/SellPage.js
Labels: design, feat

#19 Feature/meeyoung/#19
  shoppingmall/src/assets/like.svg
  shoppingmall/src/assets/pencil.svg
  shoppingmall/src/assets/unlike.svg
  shoppingmall/src/components/modal/ModalComponent.js
  shoppingmall/src/pages/productPage/ProductListPage.js
  shoppingmall/src/style/theme.js
Labels: design

#23 feature : 회원가입 기능 구현
  shoppingmall/src/assets/cart.svg
  shoppingmall/src/assets/email.svg
  shoppingmall/src/assets/mypage.svg
  shoppingmall/src/assets/password.svg
  shoppingmall/src/assets/people.svg
  shoppingmall/src/assets/phone.svg
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
Labels: feat

#28 [design]마이페이지, 장바구니 UI 구현
  shoppingmall/src/App.js
  shoppingmall/src/assets/cart.svg
  shoppingmall/src/assets/checkbox.svg
  shoppingmall/src/assets/minus.svg
  shoppingmall/src/assets/orderDetails.svg
  shoppingmall/src/assets/plus.svg
  shoppingmall/src/assets/profile.svg
  shoppingmall/src/assets/salesDetails.svg
  shoppingmall/src/assets/x-circle.svg
  shoppingmall/src/components/cart/EmptyCart.js
  shoppingmall/src/components/cart/FilledCart.js
  shoppingmall/src/components/cart/TotalSum.js
  shoppingmall/src/components/cart/productList/Count.js
  shoppingmall/src/components/cart/productList/Info.js
  shoppingmall/src/components/cart/productList/OrderAmount.js
  shoppingmall/src/components/cart/productList/ProductList.js
  shoppingmall/src/components/commom/ContentLayout.js
  shoppingmall/src/components/myPage/Info.js
  shoppingmall/src/components/myPage/MyDealList.js
  shoppingmall/src/components/myPage/Profile.js
  shoppingmall/src/pages/cart/Cart.js
  shoppingmall/src/pages/myPage/MyPage.js
Labels: design

#27 feature : 로그인 기능 구현
  shoppingmall/src/App.js
  shoppingmall/src/components/commom/AppLayout.js
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
Labels: feat

#34 design : svg 파일 수정, 사진 첨부 부분 수정
  shoppingmall/src/assets/email.svg
  shoppingmall/src/assets/home.svg
  shoppingmall/src/assets/password.svg
  shoppingmall/src/assets/people.svg
  shoppingmall/src/assets/phone.svg
  shoppingmall/src/assets/userCircle.svg
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
Labels: design, feat

#32 [design] footer, 주문 내역 UI 및 모달 구현
  shoppingmall/package-lock.json
  shoppingmall/package.json
  shoppingmall/public/index.html
  shoppingmall/src/App.js
  shoppingmall/src/components/cart/EmptyCart.js
  shoppingmall/src/components/cart/FilledCart.js
  shoppingmall/src/components/cart/TotalSum.js
  shoppingmall/src/components/cart/productList/OrderAmount.js
  shoppingmall/src/components/cart/productList/ProductList.js
  shoppingmall/src/components/commom/ContentLayout.js
  shoppingmall/src/components/commom/Modal/Modal.js
  shoppingmall/src/components/commom/Modal/ModalContainer.js
  shoppingmall/src/components/footer/Footer.js
  shoppingmall/src/components/myPage/Info.js
  shoppingmall/src/components/myPage/MyDealList.js
  shoppingmall/src/components/myPage/Profile.js
  shoppingmall/src/components/orderDetails/OrderDetailsList.js
  shoppingmall/src/hooks/useClickOutside.js
  shoppingmall/src/pages/cart/Cart.js
  shoppingmall/src/pages/myPage/MyPage.js
  shoppingmall/src/pages/orderDetails/OrderDetailsPage.js
  shoppingmall/src/style/CommonStyles.js
Labels: design, refactor, setting

#43 [design] 판매 등록 페이지 css 복원작업
  shoppingmall/src/components/productwritepage/ProductComponent.js
Labels: design

#46 [bug] pr충돌 문제로 사라진 파일들 복구
  shoppingmall/src/App.js
  shoppingmall/src/components/commom/ContentLayout.js
  shoppingmall/src/components/productList/ProductFilter.js
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/productwritepage/ProductComponent.js
  shoppingmall/src/pages/productPage/ProductListPage.js
Labels: bug

#38 feature : 회원가입 유효성 검사 추가
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
Labels: feat

#40 refactor/feature : 이미지 파일 첨부 및 미리보기
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/nav/Navigation.js
  shoppingmall/src/components/userAccount/InputField.js
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
  shoppingmall/src/components/userAccount/Vaildators.js
  shoppingmall/src/pages/loginPage/LoginPage.js
  shoppingmall/src/pages/signupPage/SignupPage.js
Labels: feat, fix, refactor

#49 [design, feat] 장바구니 페이지 UI 기능 구현
  shoppingmall/src/assets/checkedbox.svg
  shoppingmall/src/components/cart/FilledCart.js
  shoppingmall/src/components/cart/TotalSum.js
  shoppingmall/src/components/cart/productList/Count.js
  shoppingmall/src/components/cart/productList/Info.js
  shoppingmall/src/components/cart/productList/OrderAmount.js
  shoppingmall/src/components/cart/productList/ProductList.js
  shoppingmall/src/components/orderDetails/OrderDetailsList.js
  shoppingmall/src/pages/cart/Cart.js
Labels: design, feat

#51 feature 상품 상세페이지 UI 구현
  shoppingmall/package-lock.json
  shoppingmall/package.json
  shoppingmall/src/assets/profileimage.svg
  shoppingmall/src/assets/rightarrow.svg
  shoppingmall/src/components/productDetails/ProductCarousel.js
  shoppingmall/src/components/productDetails/ProductDetail.js
  shoppingmall/src/components/productDetails/ProductInfo.js
  shoppingmall/src/components/productList/ProductFilter.js
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/sellpage/PaginationArea.js
  shoppingmall/src/pages/productPage/ProductDetailPage.js
Labels: design, feat, fix

#55 feature : 로그인 , 회원가입 기능 추가
  shoppingmall/src/components/userAccount/InputField.js
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
  shoppingmall/src/components/userAccount/Vaildators.js
Labels: design, feat, fix

#58 [fix] 쇼핑몰 목록 페이지 및 상세페이지 UI 레이아웃 수정
  shoppingmall/.gitignore
  shoppingmall/src/components/productDetails/ProductDetail.js
  shoppingmall/src/components/productList/ProducFilter.js
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/style/GlobalStyle.js
Labels: design, fix

#60 [feat] api GET 요청 (마이페이지, 장바구니) & 커스텀 훅 만들기 & 로딩 스피터 공통 컴포넌트 만들기
  shoppingmall/.gitignore
  shoppingmall/package-lock.json
  shoppingmall/package.json
  shoppingmall/src/components/cart/productList/Count.js
  shoppingmall/src/components/cart/productList/Info.js
  shoppingmall/src/components/cart/productList/OrderAmount.js
  shoppingmall/src/components/cart/productList/ProductList.js
  shoppingmall/src/components/commom/EmptyContentLayout.js
  shoppingmall/src/components/myPage/Info.js
  shoppingmall/src/components/myPage/Profile.js
  shoppingmall/src/components/orderDetails/OrderDetailsList.js
  shoppingmall/src/components/sellpage/ProductArea.js
  shoppingmall/src/hooks/useFetchData.js
  shoppingmall/src/pages/cart/Cart.js
  shoppingmall/src/pages/myPage/MyPage.js
  shoppingmall/src/pages/orderDetails/OrderDetailsPage.js
  shoppingmall/src/style/CommonStyles.js
Labels: design, feat

#61 [ design ] 판매등록 페이지 UI 수정
  shoppingmall/package-lock.json
  shoppingmall/package.json
  shoppingmall/src/components/productwritepage/CompletedButton.js
  shoppingmall/src/components/productwritepage/ProductComponent.js
  shoppingmall/src/pages/ProductWritePage/ProductWritePage.js
Labels: design

#66 [fix/design] post요청, 유효성 검사 수정, 버튼 및 너비 수정
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
  shoppingmall/src/components/userAccount/Vaildators.js
Labels: design, fix

#68 보조모니터에서 100%에 맞도록 UI 수정
  shoppingmall/src/components/productDetails/ProductCarousel.js
  shoppingmall/src/components/productDetails/ProductDetail.js
  shoppingmall/src/components/productDetails/ProductInfo.js
  shoppingmall/src/components/productList/ProducFilter.js
  shoppingmall/src/components/productList/ProductFilter.js
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/sellpage/ProductArea.js
  shoppingmall/src/pages/productPage/ProductDetailPage.js
Labels: bug, design, fix

#72 상품 아이템 리스트 페이지 UI 변경 및 fetch 요청 기능 구현
  shoppingmall/src/App.js
  shoppingmall/src/components/itemList/ItemList.js
  shoppingmall/src/pages/productPage/ProductDetailPage.js
  shoppingmall/src/pages/productPage/ProductListPage.js
Labels: design, feat

#83 [feat] 장바구니 선택, 전체 주문 기능 구현
  shoppingmall/src/components/cart/FilledCart.js
  shoppingmall/src/components/cart/productList/Count.js
  shoppingmall/src/components/cart/productList/OrderAmount.js
  shoppingmall/src/components/cart/productList/ProductList.js
  shoppingmall/src/components/orderDetails/FilledOrder.js
  shoppingmall/src/components/orderDetails/OrderDetailsList.js
  shoppingmall/src/components/sellpage/ProductArea.js
  shoppingmall/src/hooks/useFetchData.js
  shoppingmall/src/pages/cart/Cart.js
  shoppingmall/src/pages/orderDetails/OrderDetailsPage.js
Labels: feat, fix

#85 [design] 메인 페이지 상품 리스트 UI, 버튼들, 레이아웃 디자인 수정
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/productDetails/ProductDetail.js
  shoppingmall/src/components/productList/ProducFilter.js
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/productwritepage/ProductComponent.js
  shoppingmall/src/components/sellpage/PaginationArea.js
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
  shoppingmall/src/pages/productPage/ProductDetailPage.js
Labels: design

#93 [feature] : 회원가입 기능 수정 및 기본 이미지 첨부 추가
  shoppingmall/src/assets/defaultImage.jpg
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/userAccount/Signup.js
Labels: feat

#99 [ fix ] 페이지 네이션 메인, 판매내역 기능 구현
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/productwritepage/ProductComponent.js
  shoppingmall/src/components/sellpage/FilterArea.js
  shoppingmall/src/components/sellpage/HeaderArea.js
  shoppingmall/src/components/sellpage/PaginationArea.js
  shoppingmall/src/components/sellpage/ProductArea.js
  shoppingmall/src/pages/ProductWritePage/ProductWritePage.js
  shoppingmall/src/pages/productModifyPage/ProductModifyPage.js
  shoppingmall/src/pages/sellPage/SellPage.js
Labels: fix

#97 [ feat ] 토큰유무 파악후 없을시 로그인으로 이동 구현 / 상품등록시 POST / 상품수정 GET, PUT / 판매내역 GE…
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/sellpage/PaginationArea.js
Labels: feat

#96 [feature] 로그인 엔터키 기능
  shoppingmall/src/components/userAccount/Login.js
Labels: feat

#101 [refactor] 이미지 불러오기, 장바구니 삭제 기능 구현, fetch 요청 token, userid 변경
  shoppingmall/src/components/cart/FilledCart.js
  shoppingmall/src/components/cart/productList/Count.js
  shoppingmall/src/components/cart/productList/Info.js
  shoppingmall/src/components/cart/productList/OrderAmount.js
  shoppingmall/src/components/cart/productList/ProductList.js
  shoppingmall/src/components/commom/Modal/Modal.js
  shoppingmall/src/components/myPage/Profile.js
  shoppingmall/src/components/orderDetails/OrderDetailsList.js
  shoppingmall/src/components/sellpage/ProductArea.js
  shoppingmall/src/hooks/useFetchData.js
  shoppingmall/src/pages/cart/Cart.js
  shoppingmall/src/pages/myPage/MyPage.js
  shoppingmall/src/pages/orderDetails/OrderDetailsPage.js
Labels: refactor

#104 [ feat ] 상품 수정페이지 value 가져와서 기입
  shoppingmall/src/components/productwritepage/ProductComponent.js
  shoppingmall/src/components/sellpage/ProductArea.js
  shoppingmall/src/pages/productModifyPage/ProductModifyPage.js
  shoppingmall/src/pages/sellPage/SellPage.js
Labels: feat

#105 fix(feature/ujin/#102): assets 파일명 변경 및 paginationArea 수정
  shoppingmall/src/components/sellpage/PaginationArea.js
  shoppingmall/src/components/sellpage/ProductArea.js
Labels: fix

#108 [design] 상품 정보, 마이페이지 UI 수정
  shoppingmall/src/components/myPage/Info.js
  shoppingmall/src/components/myPage/MyDealList.js
  shoppingmall/src/components/productDetails/ProductDetail.js
Labels: design

#110 [ feat / fix ] 모달 수정 / 상품 수정 부분 오류 픽스
  shoppingmall/src/components/productwritepage/ProductComponent.js
  shoppingmall/src/components/sellpage/HeaderArea.js
  shoppingmall/src/components/sellpage/PaginationArea.js
  shoppingmall/src/pages/sellPage/SellPage.js
Labels: feat, fix

#111 충돌해결 및 필터에서 상품등록 버튼 클릭시 로그인 유효성 검사후 페이지 이동되도록 수정
  shoppingmall/src/components/nav/Nav.js
  shoppingmall/src/components/productDetails/ProductDetail.js
  shoppingmall/src/components/productList/ProducFilter.js
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/sellpage/PaginationArea.js
  shoppingmall/src/components/sellpage/ProductArea.js
Labels: fix

#112 [fix] console.log 삭제
  shoppingmall/src/components/userAccount/Login.js
  shoppingmall/src/components/userAccount/Signup.js
Labels: fix

#114 [ fix ] 메인, 판매내역 페이지 오류 해결
  shoppingmall/src/components/productList/ProductList.js
  shoppingmall/src/components/productwritepage/ProductComponent.js
  shoppingmall/src/components/sellpage/PaginationArea.js
Labels: fix
